(* Read a graph from a file,
 * Write a graph to a file. *)

open Graph

type path = string

(* Values are read as strings. *)
val from_file: path -> string graph

(* Similarly, we write only a string graph.
 * If necessary, use gmap (to be written by you) to prepare the input graph. *)
val write_file: path -> string graph -> unit

(*Fonction qui prend en paramètre un string graph et qui l'écrit en format dot *)
(* Puisque la fonction écrit le graphe, nous utiliserons un fprintf et la fonction 
   retourne unit *)
(* nom du graphe -> graphe -> unit *)
(* Après debug il se trouve que le graphe doit être de type int graphe *)
val export: string -> int graph -> unit

(* The format of files is compatible with the files generated by:
   https://www-m9.ma.tum.de/graph-algorithms/flow-ford-fulkerson/index_en.html
*)
